Repository Nexters/boolti-web, pull requests merged in 2024-02, with the labels that each got.

#26 feat: TextField, DatePicker 컴포넌트 추가
  apps/preview/src/App.tsx
  packages/ui/src/components/Button/Button.styles.ts
  packages/ui/src/components/Button/index.tsx
  packages/ui/src/components/DatePicker/DatePicker.styles.ts
  packages/ui/src/components/DatePicker/index.tsx
  packages/ui/src/components/TextButton/index.tsx
  packages/ui/src/components/TextField/TextField.styles.ts
  packages/ui/src/components/TextField/index.tsx
  packages/ui/src/components/index.ts
Labels: 1차 MVP

#27 feat: 스토리북 설정 및 스토리들 추가
  .pnp.cjs
  .yarn/install-state.gz
  apps/preview/src/App.tsx
  apps/storybook/.gitignore
  apps/storybook/.storybook/main.ts
  apps/storybook/.storybook/preview.tsx
  apps/storybook/README.md
  apps/storybook/package.json
  apps/storybook/stories/Badge.stories.tsx
  apps/storybook/stories/Button.stories.tsx
  apps/storybook/stories/Confirm.stories.tsx
  apps/storybook/stories/DatePicker.stories.tsx
  apps/storybook/stories/Dialog.stories.tsx
  apps/storybook/stories/Footer.stories.tsx
  apps/storybook/stories/Icon.stories.mdx
  apps/storybook/stories/Palette.stories.mdx
  apps/storybook/stories/TextButton.stories.tsx
  apps/storybook/stories/TextField.stories.tsx
  apps/storybook/stories/Toast.stories.tsx
  apps/storybook/stories/emotion.d.ts
  apps/storybook/styles/index.css
  apps/storybook/tsconfig.json
  apps/storybook/vite.config.ts
  package.json
  packages/ui/src/components/TextField/TextField.styles.ts
  packages/ui/src/components/TextField/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/systems/palette.ts
  turbo.json
  yarn.lock
Labels: 1차 MVP

#32 feat: TextField 에러 있는 케이스 추가
  apps/storybook/stories/TextField.stories.tsx
  packages/ui/src/components/TextField/TextField.styles.ts
  packages/ui/src/components/TextField/index.tsx
Labels: 1차 MVP

#30 feat: 은행 관련 아이콘 추가
  apps/admin/src/pages/Login/LoginPage.tsx
  apps/storybook/stories/Button.stories.tsx
  apps/storybook/stories/Icon.stories.mdx
  apps/storybook/stories/TextButton.stories.tsx
  packages/icon/src/components/Apple.tsx
  packages/icon/src/components/ArrowLeft.tsx
  packages/icon/src/components/ArrowRIght.tsx
  packages/icon/src/components/BNK.tsx
  packages/icon/src/components/BNP.tsx
  packages/icon/src/components/BoA.tsx
  packages/icon/src/components/CB.tsx
  packages/icon/src/components/CU.tsx
  packages/icon/src/components/Calendar.tsx
  packages/icon/src/components/ChevronLeft.tsx
  packages/icon/src/components/ChevronRight.tsx
  packages/icon/src/components/ChinaCB.tsx
  packages/icon/src/components/City.tsx
  packages/icon/src/components/Clock.tsx
  packages/icon/src/components/Close.tsx
  packages/icon/src/components/DGB.tsx
  packages/icon/src/components/Deutsche.tsx
  packages/icon/src/components/EPost.tsx
  packages/icon/src/components/Edit.tsx
  packages/icon/src/components/Github.tsx
  packages/icon/src/components/HSBC.tsx
  packages/icon/src/components/Hana.tsx
  packages/icon/src/components/IBK.tsx
  packages/icon/src/components/ICBC.tsx
  packages/icon/src/components/Instagram.tsx
  packages/icon/src/components/JPMorgan.tsx
  packages/icon/src/components/K.tsx
  packages/icon/src/components/KB.tsx
  packages/icon/src/components/KDB.tsx
  packages/icon/src/components/KIS.tsx
  packages/icon/src/components/KakaoBank.tsx
  packages/icon/src/components/Kakaotalk.tsx
  packages/icon/src/components/Kwangju.tsx
  packages/icon/src/components/MG.tsx
  packages/icon/src/components/NFCF.tsx
  packages/icon/src/components/NFF.tsx
  packages/icon/src/components/NH.tsx
  packages/icon/src/components/Plus.tsx
  packages/icon/src/components/SB.tsx
  packages/icon/src/components/SBI.tsx
  packages/icon/src/components/SC.tsx
  packages/icon/src/components/Search.tsx
  packages/icon/src/components/Shinhan.tsx
  packages/icon/src/components/Ticket.tsx
  packages/icon/src/components/Toss.tsx
  packages/icon/src/components/UpDown.tsx
  packages/icon/src/components/Users.tsx
  packages/icon/src/components/Wallet.tsx
  packages/icon/src/components/Woori.tsx
  packages/icon/src/components/index.ts
  packages/ui/src/components/Dialog/index.tsx
  packages/ui/src/components/Footer/index.tsx
  packages/ui/src/components/TextField/index.tsx
Labels: 1차 MVP

#28 chore: 스토리북 다크모드 미사용
  apps/storybook/.storybook/preview.tsx
Labels: 1차 MVP

#33 fix: 아이콘 사이즈 타입 에러 수정
  apps/admin/src/components/ShowList/index.tsx
  apps/admin/src/components/ShowListItem/index.tsx
Labels: 1차 MVP

#31 chore: CODEOWNER 추가
  .github/CODEOWNERS
Labels: 1차 MVP

#36 feat: 공연 등록하기 UI 구현
  .pnp.cjs
  apps/admin/package.json
  apps/admin/src/App.tsx
  apps/admin/src/components/ShowList/index.tsx
  apps/admin/src/components/TicketForm/GeneralTicketForm.tsx
  apps/admin/src/components/TicketForm/InvitationTicketForm.tsx
  apps/admin/src/components/TicketForm/TicketForm.styles.ts
  apps/admin/src/constants/routes.ts
  apps/admin/src/pages/ShowAddPage/ShowAddPage.styles.ts
  apps/admin/src/pages/ShowAddPage/ShowAddPage.tsx
  packages/icon/src/components/FileUp.tsx
  packages/icon/src/components/index.ts
  packages/ui/src/components/TextField/TextField.styles.ts
  packages/ui/src/components/TextField/index.tsx
  packages/ui/src/systems/palette.ts
  yarn.lock
Labels: 1차 MVP

#37 feat: 피그마 바뀐 스펙 반영
  .yarn/install-state.gz
  apps/admin/src/components/AccountInfo/AccountInfo.styles.ts
  apps/admin/src/components/Layout/Layout.styles.ts
  apps/admin/src/components/SettlementDialogContent/index.tsx
  apps/admin/src/components/ShowList/ShowList.styles.ts
  apps/admin/src/components/ShowList/index.tsx
  apps/admin/src/pages/HomePage/HomePage.styles.ts
  apps/admin/src/pages/HomePage/HomePage.tsx
  packages/icon/src/components/Boolti.tsx
  packages/icon/src/components/index.ts
  packages/ui/src/components/Footer/index.tsx
Labels: 1차 MVP

#38 feat: 사용자 기본 정보 및 계좌 정보 API 연동
  apps/admin/src/components/AccountInfo/index.tsx
  apps/admin/src/components/SettlementDialogContent/SettlementDialogContent.styles.ts
  apps/admin/src/components/SettlementDialogContent/index.tsx
  apps/admin/src/components/UserProfile/UserProfile.styles.ts
  apps/admin/src/components/UserProfile/index.tsx
  apps/admin/src/constants/bankItems.ts
  apps/admin/src/pages/HomePage/HomePage.tsx
  packages/api/src/index.ts
  packages/api/src/mutations/index.ts
  packages/api/src/mutations/usePutUserSettlementAccountInfo.ts
  packages/api/src/queries/index.ts
  packages/api/src/queries/useUserAccountInfo.ts
  packages/api/src/queries/useUserSummary.ts
  packages/api/src/queryKey.ts
  packages/api/src/types/users.ts
  packages/icon/src/components/Citi.tsx
  packages/icon/src/components/UserProfile.tsx
  packages/icon/src/components/index.ts
  packages/ui/src/components/DatePicker/DatePicker.styles.ts
  packages/ui/src/components/TextField/index.tsx
Labels: 1차 MVP

#39 feat: ShowDetailHeader 컴포넌트 구현
  .pnp.cjs
  apps/admin/package.json
  apps/admin/src/App.tsx
  apps/admin/src/components/Layout/Layout.styles.ts
  apps/admin/src/components/Layout/index.tsx
  apps/admin/src/components/ShowDetailLayout/ShowDetailLayout.styles.ts
  apps/admin/src/components/ShowDetailLayout/index.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowBasicInfoFormContent.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowDetailInfoForm.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowInfoForm.styles.ts
  apps/admin/src/constants/routes.ts
  apps/admin/src/pages/ShowInfoPage/ShowInfoPage.styles.ts
  apps/admin/src/pages/ShowInfoPage/ShowInfoPage.tsx
  yarn.lock
Labels: 1차 MVP

#41 feat: 공연 기본 정보 기능 구현
  apps/admin/src/App.tsx
  apps/admin/src/components/ShowDeleteForm/ShowDeleteForm.styles.ts
  apps/admin/src/components/ShowDeleteForm/index.tsx
  apps/admin/src/components/ShowDetailLayout/ShowDetailLayout.styles.ts
  apps/admin/src/components/ShowDetailLayout/index.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowBasicInfoFormContent.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowDetailInfoForm.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowDetailInfoFormContent.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowInfoForm.styles.ts
  apps/admin/src/components/ShowInfoFormContent/ShowInfoFormContent.styles.ts
  apps/admin/src/components/ShowInfoFormContent/ShowInvitationTicketFormContent.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowSalesTicketFormContent.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowTicketInfoFormContent.tsx
  apps/admin/src/components/ShowInfoFormContent/types.ts
  apps/admin/src/components/TicketForm/SalesTicketForm.tsx
  apps/admin/src/pages/ShowAddPage/ShowAddPage.styles.ts
  apps/admin/src/pages/ShowAddPage/ShowAddPage.tsx
  apps/admin/src/pages/ShowInfoPage/ShowInfoPage.styles.ts
  apps/admin/src/pages/ShowInfoPage/ShowInfoPage.tsx
  apps/admin/src/pages/ShowTicketPage/ShowTicketPage.styles.ts
  apps/admin/src/pages/ShowTicketPage/ShowTicketPage.tsx
  packages/api/src/index.ts
  packages/api/src/mutations/index.ts
  packages/api/src/mutations/useDeleteShow.ts
  packages/api/src/mutations/useEditShowInfo.ts
  packages/api/src/mutations/useUploadShowImage.ts
  packages/api/src/queries/index.ts
  packages/api/src/queries/useShowSalesInfo.ts
  packages/api/src/queryKey.ts
  packages/api/src/types/index.ts
  packages/api/src/types/show.ts
  packages/ui/src/components/Confirm/Confirm.styles.ts
  packages/ui/src/components/Dialog/Dialog.styles.ts
  packages/ui/src/components/TextField/TextField.styles.ts
  packages/ui/src/components/TextField/index.tsx
  packages/ui/src/hooks/useToast.tsx
Labels: 1차 MVP

#43 feat: 사이트 메타 데이터 추가
  .pnp.cjs
  .yarn/install-state.gz
  apps/admin/src/App.tsx
  apps/storybook/stories/Icon.stories.mdx
  apps/storybook/stories/images.d.ts
  packages/ui/package.json
  packages/ui/src/assets/favicon.png
  packages/ui/src/assets/thumbnail.png
  packages/ui/src/components/Meta/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/images.d.ts
  yarn.lock
Labels: 1차 MVP

#44 feat: 관객 입장 확인 다이얼로그 컴포넌트 추가
  apps/admin/public/code.png
  apps/admin/public/qr.png
  apps/admin/src/components/EntranceConfirmDialogContent/EntranceConfirmDialogContent.styles.ts
  apps/admin/src/components/EntranceConfirmDialogContent/index.tsx
  apps/admin/src/components/ShowList/ShowList.styles.ts
  apps/admin/src/components/ShowList/index.tsx
  packages/ui/src/components/Dialog/Dialog.styles.ts
  packages/ui/src/components/Dialog/index.tsx
  packages/ui/src/components/DialogProvider/index.tsx
  packages/ui/src/contexts/dialogContext.ts
  packages/ui/src/hooks/useDialog.ts
Labels: 1차 MVP

#46 fix: 메타 태그 추가 수정
  packages/ui/src/components/Meta/index.tsx
Labels: 1차 MVP

#49 fix: 이모지 제거, 링크 수정
  apps/admin/index.html
Labels: 1차 MVP

#50 feat: 티켓 관리 페이지 UI 구성 및 API 연동
  apps/admin/src/components/ShowDetailLayout/index.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowBasicInfoFormContent.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowInfoFormContent.styles.ts
  apps/admin/src/components/ShowInfoFormContent/ShowInvitationCodeList.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowInvitationTicketFormContent.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowSalesTicketFormContent.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowTicketInfoFormContent.tsx
  apps/admin/src/components/TicketForm/InvitationTicketForm.tsx
  apps/admin/src/components/TicketForm/SalesTicketForm.tsx
  apps/admin/src/pages/ShowAddPage/ShowAddPage.tsx
  apps/admin/src/pages/ShowInfoPage/ShowInfoPage.tsx
  apps/admin/src/pages/ShowTicketPage/ShowTicketPage.styles.ts
  apps/admin/src/pages/ShowTicketPage/ShowTicketPage.tsx
  packages/api/src/mutations/index.ts
  packages/api/src/mutations/useCreateInvitationTicket.ts
  packages/api/src/mutations/useCreateSalesTicket.ts
  packages/api/src/mutations/useDeleteInvitationTicket.ts
  packages/api/src/mutations/useDeleteSalesTicket.ts
  packages/api/src/mutations/useEditSalesTicketInfo.tsx
  packages/api/src/queries/index.ts
  packages/api/src/queries/useInvitationCodeList.ts
  packages/api/src/queries/useInvitationTicketList.ts
  packages/api/src/queries/useSalesTicketList.ts
  packages/api/src/queryKey.ts
  packages/api/src/types/show.ts
  packages/icon/src/components/ChevronDown.tsx
  packages/icon/src/components/ChevronUp.tsx
  packages/icon/src/components/index.ts
Labels: 1차 MVP

#53 feat: 푸터 변경사항 반영
  packages/ui/src/components/Footer/index.tsx
Labels: 1차 MVP

#52 feat: 예매자 관리 페이지
  .pnp.cjs
  .yarn/install-state.gz
  apps/admin/package.json
  apps/admin/src/App.tsx
  apps/admin/src/components/ShowList/index.tsx
  apps/admin/src/components/ShowListItem/index.tsx
  apps/admin/src/components/TicketTypeSelect/index.tsx
  apps/admin/src/pages/ShowEnteryPage/ShowEnterancePage.tsx
  apps/admin/src/pages/ShowEnteryPage/ShowEnteryPage.styles.ts
  apps/admin/src/pages/ShowReservationPage/ShowReservationPage.styles.ts
  apps/admin/src/pages/ShowReservationPage/ShowReservationPage.tsx
  apps/storybook/stories/Icon.stories.mdx
  packages/api/src/queries/index.ts
  packages/api/src/queries/useShowReservationSummary.ts
  packages/api/src/queries/useShowReservations.ts
  packages/api/src/queryKey.ts
  packages/api/src/types/show.ts
  packages/config-eslint/index.js
  packages/icon/src/components/Clear.tsx
  packages/icon/src/components/index.ts
  yarn.lock
Labels: 1차 MVP

#54 feat: 아이콘 갤러리 간결화
  apps/storybook/stories/Icon.stories.mdx
Labels: 1차 MVP

#55 fix: 공연 등록 시 클릭 횟수에 따라 submit 이벤트가 발생하는 문제 수정
  apps/admin/src/pages/ShowAddPage/ShowAddPage.tsx
Labels: 1차 MVP

#56 feat: 환경 변수 기반 API 엔드포인트 설정
  apps/admin/src/vite-env.d.ts
  packages/api/src/fetcher.ts
  packages/api/src/vite-env.d.ts
Labels: 1차 MVP

#57 feat: 예매자 관리 페이지 작업 2
  .pnp.cjs
  .yarn/install-state.gz
  apps/admin/package.json
  apps/admin/src/components/Pagination/Pagination.styles.ts
  apps/admin/src/components/Pagination/index.tsx
  apps/admin/src/components/ReservationTable/ReservationTable.styles.ts
  apps/admin/src/components/ReservationTable/index.tsx
  apps/admin/src/pages/ShowReservationPage/ShowReservationPage.styles.ts
  apps/admin/src/pages/ShowReservationPage/ShowReservationPage.tsx
  apps/admin/src/utils/format.ts
  packages/api/src/queries/useShowReservations.ts
  packages/api/src/queryKey.ts
  packages/api/src/types/show.ts
  yarn.lock
Labels: 1차 MVP

#58 feat: 페이지네이션 10개 넘을 경우 대응
  apps/admin/src/components/Pagination/index.tsx
  apps/admin/src/components/ReservationTable/ReservationTable.styles.ts
  apps/admin/src/components/ReservationTable/index.tsx
  apps/admin/src/pages/ShowAddPage/ShowAddPage.tsx
  apps/admin/src/pages/ShowReservationPage/ShowReservationPage.tsx
Labels: 1차 MVP

#59 feat: 입장 관리 페이지
  apps/admin/src/App.tsx
  apps/admin/src/components/EnteranceTable/EnteranceTable.styles.ts
  apps/admin/src/components/EnteranceTable/index.tsx
  apps/admin/src/components/ShowDetailLayout/index.tsx
  apps/admin/src/constants/routes.ts
  apps/admin/src/pages/ShowEnterancePage/ShowEnterancePage.styles.ts
  apps/admin/src/pages/ShowEnterancePage/index.tsx
  apps/admin/src/pages/ShowEnteryPage/ShowEnterancePage.tsx
  apps/admin/src/pages/ShowEnteryPage/ShowEnteryPage.styles.ts
  apps/admin/src/pages/ShowReservationPage/index.tsx
  packages/api/src/queries/index.ts
  packages/api/src/queries/useShowEnteranceInfo.ts
  packages/api/src/queries/useShowEnteranceSummary.ts
  packages/api/src/queries/useShowEnterances.ts
  packages/api/src/queryKey.ts
  packages/api/src/types/common.ts
  packages/api/src/types/entrance.ts
  packages/api/src/types/index.ts
  packages/api/src/types/show.ts
Labels: 1차 MVP

#60 fix: 테이블 잘려도 스크롤되게 설정
  apps/admin/src/components/EnteranceTable/EnteranceTable.styles.ts
  apps/admin/src/components/ReservationTable/ReservationTable.styles.ts
  apps/admin/src/components/ReservationTable/index.tsx
Labels: 1차 MVP

#61 fix: 결제수단 노출 버그 수정
  apps/admin/src/components/ReservationTable/index.tsx
Labels: bug

#62 fix: means 필드 이용하도록 수정
  apps/admin/src/components/ReservationTable/index.tsx
Labels: bug

#63 fix: 페이지네이션 오류 수정, 이미지 순서 수정 등
  apps/admin/src/components/EnteranceTable/EnteranceTable.styles.ts
  apps/admin/src/components/EnteranceTable/index.tsx
  apps/admin/src/components/EntranceConfirmDialogContent/index.tsx
  apps/admin/src/components/ReservationTable/ReservationTable.styles.ts
  apps/admin/src/components/ReservationTable/index.tsx
  apps/admin/src/pages/ShowEnterancePage/ShowEnterancePage.styles.ts
  apps/admin/src/pages/ShowEnterancePage/index.tsx
  apps/admin/src/pages/ShowReservationPage/ShowReservationPage.styles.ts
  apps/admin/src/pages/ShowReservationPage/index.tsx
  packages/api/src/queries/useShowEnterances.ts
  packages/api/src/queries/useShowReservations.ts
  packages/api/src/queryKey.ts
Labels: bug

#64 fix: 테이블 관련 버그 및 문구 수정
  apps/admin/src/components/ReservationTable/index.tsx
  apps/admin/src/pages/ShowEnterancePage/index.tsx
  apps/admin/src/pages/ShowReservationPage/index.tsx
Labels: bug

#65 feat: 공연 티켓 판매 중에도 공연 정보를 수정할 수 있도록 수정
  apps/admin/src/pages/ShowInfoPage/ShowInfoPage.tsx
Labels: 2차 MVP

#66 feat: 애플 로그인 구현 및 개발 서버 host 변경
  .pnp.cjs
  apps/admin/index.html
  apps/admin/package.json
  apps/admin/src/pages/Login/LoginPage.tsx
  apps/admin/vite.config.ts
  packages/api/src/mutations/index.ts
  packages/api/src/mutations/useAppleLogin.ts
  packages/api/src/mutations/useKakaoToken.ts
  yarn.lock
Labels: 2차 MVP

#67 feat: 티켓 판매가 시작되었어도 티켓이 판매되지 않았다면 삭제할 수 있도록 수정
  apps/admin/src/components/ShowInfoFormContent/ShowInvitationTicketFormContent.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowSalesTicketFormContent.tsx
  apps/admin/src/pages/ShowTicketPage/ShowTicketPage.tsx
Labels: 2차 MVP

#68 feat: 푸터 반응형 적용
  .pnp.cjs
  .yarn/install-state.gz
  packages/api/package.json
  packages/api/src/QueryClientProvider.tsx
  packages/ui/src/components/Footer/Footer.styles.ts
  packages/ui/src/components/Footer/index.tsx
  packages/ui/src/systems/breakpoint.ts
  packages/ui/src/systems/index.ts
  yarn.lock
Labels: 2차 MVP

#70 feat: 입장 확인 방법 안내 다이얼로그 반응형 대응
  .pnp.cjs
  .yarn/install-state.gz
  apps/admin/package.json
  apps/admin/src/components/EntranceConfirmDialogContent/EntranceConfirmDialogContent.styles.ts
  apps/admin/src/components/EntranceConfirmDialogContent/index.tsx
  apps/admin/src/components/ShowList/index.tsx
  apps/admin/src/hooks/useDeviceWidth.ts
  apps/admin/src/pages/ShowEnterancePage/index.tsx
  packages/ui/src/components/Dialog/Dialog.styles.ts
  packages/ui/src/components/Dialog/index.tsx
  yarn.lock
Labels: 2차 MVP

#72 feat: 로그인 페이지 반응형 적용
  apps/admin/src/components/ShowListItem/index.tsx
  apps/admin/src/constants/routes.ts
  apps/admin/src/pages/Login/LoginPage.styles.ts
  apps/admin/src/pages/Login/LoginPage.tsx
  apps/admin/src/pages/SignUpComplete/SignUpCompletePage.styles.ts
  apps/admin/src/pages/SignUpComplete/SignUpCompletePage.tsx
Labels: 2차 MVP

#73 feat: 공연 상세 미리보기 구현
  .gitignore
  .pnp.cjs
  .yarn/install-state.gz
  apps/admin/package.json
  apps/admin/src/App.tsx
  apps/admin/src/components/ShowPreview/ShowPreview.styles.ts
  apps/admin/src/components/ShowPreview/ShowPreviewNotice.styles.ts
  apps/admin/src/components/ShowPreview/ShowPreviewNotice.tsx
  apps/admin/src/components/ShowPreview/index.tsx
  apps/admin/src/index.css
  apps/admin/src/pages/ShowInfoPage/PreviewFrame.tsx
  apps/admin/src/pages/ShowInfoPage/ShowInfoPage.styles.ts
  apps/admin/src/pages/ShowInfoPage/ShowInfoPage.tsx
  packages/ui/package.json
  packages/ui/src/components/Drawer/Drawer.styles.ts
  packages/ui/src/components/Drawer/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/systems/palette.ts
  packages/ui/src/systems/typo.ts
  yarn.lock
Labels: 2차 MVP

#74 feat: 예매자 관리, 입장관리 상단 요약 및 필터 모바일 대응
  apps/admin/src/components/TicketTypeSelect/index.tsx
  apps/admin/src/pages/ShowEnterancePage/ShowEnterancePage.styles.ts
  apps/admin/src/pages/ShowEnterancePage/index.tsx
  apps/admin/src/pages/ShowReservationPage/ShowReservationPage.styles.ts
  apps/admin/src/pages/ShowReservationPage/index.tsx
Labels: 2차 MVP

#76 feat: 티켓 타입 리셋 기능 추가
  apps/admin/src/components/TicketTypeSelect/index.tsx
  apps/admin/src/pages/ShowEnterancePage/index.tsx
  apps/admin/src/pages/ShowReservationPage/index.tsx
Labels: 2차 MVP

#77 feat: CS용 예매, 티켓 아이디 추가
  apps/admin/src/components/EnteranceTable/index.tsx
  apps/admin/src/components/ReservationTable/index.tsx
  packages/api/src/types/entrance.ts
  packages/api/src/types/show.ts
Labels: 2차 MVP

#78 feat: 공연 기본 정보 및 티켓 관리 페이지 모바일 대응 / QA 버그 수정
  apps/admin/src/components/Header/Header.styles.ts
  apps/admin/src/components/Layout/Layout.styles.ts
  apps/admin/src/components/ShowDetailLayout/ShowDetailLayout.styles.ts
  apps/admin/src/components/ShowDetailLayout/index.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowInfoFormContent.styles.ts
  apps/admin/src/components/ShowInfoFormContent/ShowInvitationCodeList.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowInvitationTicketFormContent.tsx
  apps/admin/src/components/ShowInfoFormContent/ShowSalesTicketFormContent.tsx
  apps/admin/src/pages/ShowInfoPage/ShowInfoPage.styles.ts
  apps/admin/src/pages/ShowInfoPage/ShowInfoPage.tsx
  apps/admin/src/pages/ShowTicketPage/ShowTicketPage.styles.ts
  apps/admin/src/pages/ShowTicketPage/ShowTicketPage.tsx
  packages/ui/src/components/Confirm/Confirm.styles.ts
Labels: 2차 MVP
